### ISSUE TITLE
tensorflow wheel

### ISSUE THREAD

**Issue by xuzhang5788** [mkusner/grammarVAE#10]
I am using tensorflow 1.8.0. I want to change .whl from cpu to gpu. But I don't know the right .whl file is. Could you provide new .whl file? Many thanks.

**Comment by mkusner** [comment]
Hey xuzhang! Here are the URL's for various tensorflow versions: https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package

**Comment by xuzhang5788** [comment]
Thank you very much!
I found a right .whl file for my python 3.5 and tensorflow 1.8.0 and change line 4 in requirements.txt and 

$pip install -r requirements.txt

but I got the following error messages:
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bvfdv6qe/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/tmp/pip-install-bvfdv6qe/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/tmp/pip-install-bvfdv6qe/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/home/xuzhang/anaconda3/lib/python3.5/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bvfdv6qe/progressbar/
 
Your help is highly appreciated.
